### ISSUE TITLE
latest version of terra classic which you can find the repos as well

### ISSUE THREAD

**Issue by nikos9595** [mint-cash/LocalTerra#2]
https://github.com/classic-terra

**Comment by minjaesheep** [comment]
Hey thanks! We'll try to use the client there. Updated #1's title.

**Comment by nikos9595** [comment]
> Hey thanks! We'll try to use the client there. Updated #1's title.
keep in mind this repo u using is outdate its no use for terra classic


https://discord.gg/bFPCDs66PQ
in this discord you can ge t in contact with devs on  lunc classic to help you with everything

**Comment by nikos9595** [comment]
> Hey thanks! We'll try to use the client there. Updated #1's title.

@minjaesheep talk with strathcole he might help you as well ! you ll find all the upgradfe that happened the latest days from genius labs (i think they are from korea or china ) ... we made a lot of upgrades lately
